memo/Models/Offer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace memo.Models
{
    [Table("Offer", Schema = "memo")]
    public partial class Offer
    {
        public Offer()
        {
            OfferStatusId = 1;  // Default: Ceka
            SharedInfo = new SharedInfo();
        }

        [Key]
        [Display(Name = "ID")]
        public int OfferId { get; set; }

        public int SharedInfoId { get; set; }
        public virtual SharedInfo SharedInfo { get; set; }

        [Required]
        [Display(Name = "Ev. číslo nabídky"), StringLength(50)]
        [RegularExpression(@"^EV[E]?-quo/\d{4}/\d{4}$", ErrorMessage = "Číslo nabídky musí být ve tvaru EV(E)-quo/rrrr/####, kde rrrr je rok a #### pořadové unikátní číslo")]
        public string OfferName { get; set; }

        [Display(Name = "Datum odeslání nabídky"), Column(TypeName = "date"), DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? SentDate { get; set; }

        [NotMapped]
        public List<SelectListItem> EveDivisionList { get; } = new List<SelectListItem>
        {
            new SelectListItem { Value = "EVE", Text = "EVE" },
            new SelectListItem { Value = "EVAT", Text = "EVAT" },
        };

        [Display(Name = "Status nabídky")]
        public int OfferStatusId { get; set; }
        public virtual OfferStatus OfferStatus { get; set; }

        [Display(Name = "Důvod prohry"), Column(TypeName = "nvarchar(max)")]
        public string LostReason { get; set; }

        [Display(Name = "Poznámky"), Column(TypeName = "nvarchar(max)")]
        public string Notes { get; set; }

        [Display(Name = "Vytvořil"), StringLength(50)]
        public string CreatedBy { get; set; }

        [Display(Name = "Upravil"), StringLength(50)]
        public string ModifiedBy { get; set; }

        [Display(Name = "Datum vytvoření"), Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }

        [Display(Name = "Poslední úprava"), Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [Display(Name = "Aktivní")]
        public Boolean Active { get; set; } = true;  // Default: Active


        public virtual List<Order> Orders { get; set; }
    }
}

memo/ViewModels/OfferViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using memo.Models;

namespace memo.ViewModels
{
    public class OfferViewModel
    {
        // public int OfferId { get; set; }
        // public string Name { get; set; }

        // public int CompanyId { get; set; }
        // public IEnumerable<Company> CompanyList { get; set; }

        // public int ContactId { get; set; }
        // public IEnumerable<Contact> ContactList { get; set; }

        public Offer Offer { get; set; }
        public IEnumerable<AuditViewModel> Audits { get; set; }

        // SelectLists
        public IEnumerable<SelectListItem> CompanyList { get; set; }
        public IEnumerable<SelectListItem> DepartmentList { get; set; }
        public IEnumerable<SelectListItem> EveContactList { get; set; }
        public IEnumerable<SelectListItem> ContactList { get; set; }
        public IEnumerable<SelectListItem> CurrencyList { get; set; }
        public IEnumerable<SelectListItem> CurrencyListNoRate { get; set; }
        public List<SelectListItem> EveDivisionList { get; set; } = new List<SelectListItem>()
        {
            new SelectListItem { Value = "EVE", Text = "EVE" },
            new SelectListItem { Value = "EVAT", Text = "EVAT" },
        };
    }
}

memo/Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using memo.Data;
using memo.Models;
using memo.ViewModels;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Hosting;

namespace memo.Controllers
{
    public class OffersController : BaseController
    {
        public ApplicationDbContext _db { get; }
        public EvektorDbContext _eveDb { get; }
        public EvektorDochnaDbContext _eveDbDochna { get; }
        protected readonly IWebHostEnvironment _env;

        public OffersController(ApplicationDbContext db,
                                EvektorDbContext eveDb,
                                EvektorDochnaDbContext eveDbDochna,
                                IWebHostEnvironment hostEnvironment) : base(hostEnvironment)
        {
            _db = db;
            _eveDb = eveDb;
            _eveDbDochna = eveDbDochna;
            _env = hostEnvironment;
        }

        public async Task<IActionResult> Index(bool showInactive = false)
        {
            ViewBag.showInactive = showInactive;

            Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();

            List<Offer> offers = await _db.Offer
                // .Include(x => x.SharedInfo)
                //     .ThenInclude(y => y.Contact)
                // .Include(x => x.SharedInfo)
                //     .ThenInclude(y => y.Company)
                // .Include(x => x.SharedInfo)
                //     .ThenInclude(y => y.Currency)
                // .Include(x => x.SharedInfo.Contact)
                // .Include(x => x.SharedInfo.Company)
                // .Include(x => x.SharedInfo.Currency)
                .Include(a => a.OfferStatus)
                .ToListAsync();

            await _db.SharedInfo.LoadAsync();
            await _db.Contact.LoadAsync();
            await _db.Company.LoadAsync();
            await _db.Currency.LoadAsync();

            if (showInactive is false)
            {
                offers = offers.Where(x => x.Active == true).ToList();
            }

            List<Order> allOrders = await _db.Order.ToListAsync();
            ViewBag.AllOrders = allOrders;

            List<Offer> allOffers = await _db.Offer.ToListAsync();
            ViewBag.AllOffersCount = allOffers.Count();

            TimeSpan ts = stopwatch.Elapsed;
            string message = string.Format("Stránka načtena za: {0:D1}.{1:D3}s", ts.Seconds, ts.Milliseconds);
            if (_env.IsDevelopment())
            {
                TempData["Info"] = message;
            }

            return View(offers);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            Offer offer = new Offer();

            offer.SharedInfo.ReceiveDate = DateTime.Now;
            offer.SharedInfo.ExchangeRate = decimal.Parse(getCurrencyStr("CZK"));
            offer.OfferName = await getNewOfferNumAsync();

            OfferViewModel vm = new OfferViewModel()
            {
                Offer = offer,
            };

            await populateModelAsync(vm);
            await defaultEvePreselected(vm);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Offer offer)
        {
            // offer.OfferName = getNewOfferNum();  // TODO Tohle vratit zpet, az tam budou vsechny aktualni
            string exchangeRateText = await _db.Currency.Where(x => x.CurrencyId == offer.SharedInfo.CurrencyId).Select(x => x.Name).FirstOrDefaultAsync();
            Decimal ExchangeRate = Convert.ToDecimal(getCurrencyStr(exchangeRateText));

            if (offer.SharedInfo.Price != null)
            {
                offer.SharedInfo.PriceCzk = Convert.ToInt32(offer.SharedInfo.Price * ExchangeRate);  // 1000 * 26,243
            }

            if (ModelState.IsValid)
            {
                offer.CreatedBy = User.GetLoggedInUserName();
                offer.CreatedDate = DateTime.Now;
                offer.ModifiedBy = offer.CreatedBy;
                offer.ModifiedDate = offer.CreatedDate;

                await _db.AddAsync(offer);
                await _db.SaveChangesAsync(User.GetLoggedInUserName());

                TempData["Success"] = "Vytvoření bylo úspěšné";
                OfferViewModel vmm = new OfferViewModel()
                {
                    Offer = offer,
                };

                return RedirectToAction("Index");
            }

            OfferViewModel vm = new OfferViewModel()
            {
                Offer = offer,
            };

            await populateModelAsync(vm);
            await defaultEvePreselected(vm);
            TempData["Error"] = "Nepovedlo se uložit.";

            return View(vm);
        }

        // GET: Offer/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Offer offer = await _db.Offer
                .Include(x => x.SharedInfo)
                .FirstOrDefaultAsync(x => x.OfferId == id);

            if (offer == null)
            {
                return NotFound();
            }

            List<AuditViewModel> audits = getAuditViewModel(_db).Audits
                .Where(x => x.TableName == "Offer" && x.KeyValue == id.ToString())
                .ToList();

            OfferViewModel vm = new OfferViewModel()
            {
                Offer = offer,
                Audits = audits,
            };

            await populateModelAsync(vm);

            ViewBag.OfferStatusName = _db.OfferStatus.Find(offer.OfferStatusId).Name;
            ViewBag.CreatedOrders = _db.Order.Include(x => x.Offer).Where(x => x.OfferId == id).ToList();

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string actionType, int id, OfferViewModel vm)
        {
            if (ModelState.IsValid)
            {
                OfferViewModel oldVm = new OfferViewModel();
                oldVm.Offer = await _db.Offer
                    .AsNoTracking()
                    .Include(x => x.SharedInfo).
                    FirstOrDefaultAsync(x => x.OfferId == vm.Offer.OfferId);

                if (oldVm.Offer.OfferName == vm.Offer.OfferName &&
                    oldVm.Offer.SharedInfo.ReceiveDate == vm.Offer.SharedInfo.ReceiveDate &&
                    oldVm.Offer.SharedInfo.EstimatedFinishDate == vm.Offer.SharedInfo.EstimatedFinishDate &&
                    oldVm.Offer.SentDate == vm.Offer.SentDate &&
                    oldVm.Offer.SharedInfo.Subject == vm.Offer.SharedInfo.Subject &&
                    oldVm.Offer.SharedInfo.ContactId == vm.Offer.SharedInfo.ContactId &&
                    oldVm.Offer.SharedInfo.CompanyId == vm.Offer.SharedInfo.CompanyId &&
                    oldVm.Offer.SharedInfo.EveDivision == vm.Offer.SharedInfo.EveDivision &&
                    oldVm.Offer.SharedInfo.EveDepartment == vm.Offer.SharedInfo.EveDepartment &&
                    oldVm.Offer.SharedInfo.EveCreatedUser == vm.Offer.SharedInfo.EveCreatedUser &&
                    oldVm.Offer.SharedInfo.Price == vm.Offer.SharedInfo.Price &&
                    oldVm.Offer.SharedInfo.CurrencyId == vm.Offer.SharedInfo.CurrencyId &&
                    oldVm.Offer.SharedInfo.ExchangeRate == vm.Offer.SharedInfo.ExchangeRate &&
                    oldVm.Offer.LostReason == vm.Offer.LostReason &&
                    oldVm.Offer.Notes == vm.Offer.Notes &&
                    oldVm.Offer.Active == vm.Offer.Active)
                {
                    TempData["Info"] = "Nebyla provedena změna, není co uložit";

                    if (actionType == "Uložit")
                    {
                        // Populate VM
                        vm.Audits = getAuditViewModel(_db).Audits
                            .Where(x => x.TableName == "Offer" && x.KeyValue == id.ToString())
                            .ToList();

                        await populateModelAsync(vm);

                        ViewBag.OfferStatusName = _db.OfferStatus.Find(vm.Offer.OfferStatusId).Name;
                        ViewBag.CreatedOrders = _db.Order.Include(x => x.Offer).ThenInclude(x => x.SharedInfo).Where(x => x.OfferId == id).ToList();

                        vm.Offer.SharedInfo = await _db.SharedInfo
                            .Where(x => x.SharedInfoId == vm.Offer.SharedInfoId)
                            .Include(x => x.Company)
                            .Include(x => x.Contact)
                            .FirstOrDefaultAsync();

                        return View(vm);
                    }
                    else
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }

                if (vm.Offer.SharedInfo.Price != null)
                {
                    string exchangeRateText = await _db.Currency.Where(x => x.CurrencyId == vm.Offer.SharedInfo.CurrencyId).Select(x => x.Name).FirstOrDefaultAsync();
                    Decimal ExchangeRate = Convert.ToDecimal(getCurrencyStr(exchangeRateText));

                    vm.Offer.SharedInfo.PriceCzk = Convert.ToInt32(vm.Offer.SharedInfo.Price * ExchangeRate);  // 1000 * 26,243
                }
                vm.Offer.ModifiedBy = User.GetLoggedInUserName();
                vm.Offer.ModifiedDate = DateTime.Now;

                _db.Update(vm.Offer);
                await _db.SaveChangesAsync(User.GetLoggedInUserName());

                TempData["Success"] = "Editace uložena";

                if (actionType == "Uložit")
                {
                    // Populate VM
                    vm.Audits = getAuditViewModel(_db).Audits

memo/Views/Offers/Create.cshtml
@{
    ViewData["Title"] = "Nová nabídka";
}

@model memo.ViewModels.OfferViewModel

@await Html.PartialAsync("_Partial_ToastNotification")

<div class="text-center">
    <h1 class="display-6">@ViewData["Title"]</h1>
    <hr />
</div>

<div class="container d-flex justify-content-center">
    <div class="col-lg-10 personal-info">
        <form class="card" role="form" autocomplete="on" asp-action="Create" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group row">
            <label asp-for="Offer.OfferName" class="required col-lg-3 col-form-label form-control-label control-label"></label>
            <div class="col-lg-9">
                <span class="has-float-label">
                    <input asp-for="Offer.OfferName" class="form-control" placeholder="EV(E)-quo/rrrr/dddd" type="text" />
                    <label asp-for="Offer.OfferName"></label>
                </span>
                <span asp-validation-for="Offer.OfferName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Offer.SharedInfo.ReceiveDate" class="required col-lg-3 col-form-label form-control-label control-label"></label>
            <div class="col-lg-9 mycalendar">
                <span class="has-float-label">
                    <input asp-for="Offer.SharedInfo.ReceiveDate" class="form-control" type="text" placeholder=" " required="" autocomplete="off"/>
                    <label asp-for="Offer.SharedInfo.ReceiveDate">Datum přijetí poptávky</label>
                </span>
                <span asp-validation-for="Offer.SharedInfo.ReceiveDate" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Offer.SentDate" class="col-lg-3 col-form-label form-control-label control-label"></label>
            <div class="col-lg-9 mycalendar">
                <span class="has-float-label">
                    <input asp-for="Offer.SentDate" class="form-control" type="text" placeholder=" " autocomplete="off"/>
                    <label asp-for="Offer.SentDate">Datum odeslání nabídky</label>
                </span>
                <span asp-validation-for="Offer.SentDate" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Offer.SharedInfo.Subject" class="required col-lg-3 col-form-label form-control-label control-label"></label>
            <div class="col-lg-9">
                <span class="has-float-label">
                    <input asp-for="Offer.SharedInfo.Subject" class="form-control" placeholder="Krátký popis nabídky" type="text" />
                    <label asp-for="Offer.SharedInfo.Subject">Předmět nabídky</label>
                </span>
                <span asp-validation-for="Offer.SharedInfo.Subject" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row eveOffer">
            <label class="col-lg-3 col-form-label form-control-label control-label">Evektor</label>
            <div class="col-lg-2">
                <span class="floating-select-label">Divize</span>
                <select class="form-control" asp-for="Offer.SharedInfo.EveDivision" asp-items="@Model.Offer.EveDivisionList"></select>
                <span asp-validation-for="Offer.SharedInfo.EveDivision" class="text-danger"></span>
            </div>
            <div class="col-lg-3">
                <span class="floating-select-label">Oddělení</span>
                <select asp-for="Offer.SharedInfo.EveDepartment" class="form-control select-department-ajax"></select>
                <span asp-validation-for="Offer.SharedInfo.EveDepartment" class="text-danger"></span>
            </div>
            <div class="col-lg-4">
                <span class="floating-select-label">Uživatel</span>
                <select asp-for="Offer.SharedInfo.EveCreatedUser" class="form-control select-user-ajax"></select>
                <span asp-validation-for="Offer.SharedInfo.EveCreatedUser" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row customerOffer">
            <label class="required col-lg-3 col-form-label form-control-label control-label">Zákazník</label>
            <div class="col-lg-4">
                <span class="floating-select-label">Firma zákazníka</span>
                <select asp-for="Offer.SharedInfo.CompanyId" class="form-control select-company-ajax"></select>
                <span asp-validation-for="Offer.SharedInfo.CompanyId" class="text-danger"></span>
            </div>
            <div class="col-lg-1" data-toggle="tooltip" title="Nová firma">
                <a asp-action="create" asp-controller="Companies" target="_blank">
                    <i class="form-control fa fa-plus-circle" style="color: green; cursor: pointer;"></i>
                </a>
            </div>
            <div class="col-lg-3">
                <span class="floating-select-label">Kontakt</span>
                <select asp-for="Offer.SharedInfo.ContactId" class="form-control select-contact-ajax"></select>
                <span asp-validation-for="Offer.SharedInfo.ContactId" class="text-danger"></span>
            </div>
            <div class="col-lg-1" data-toggle="tooltip" title="Nový kontakt">
                <a asp-action="create" asp-controller="Contacts" class="modular-company-id" target="_blank">
                    <i class="form-control fa fa-plus-circle" style="color: green; cursor: pointer;"></i>
                </a>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Offer.SharedInfo.Price" class="required col-lg-3 col-form-label form-control-label control-label"></label>
            <div class="col-lg-5">
                <span class="has-float-label">
                    <input asp-for="Offer.SharedInfo.Price" class="form-control" type="text" placeholder=" "/>
                    <label asp-for="Offer.SharedInfo.Price">Cena bez DPH</label>
                </span>
                <span asp-validation-for="Offer.SharedInfo.Price" class="text-danger"></span>
            </div>
            <div class="col-lg-4">
                <span class="has-float-label" data-toggle="tooltip" title="Aktuální kurz ČNB">
                    <select asp-for="Offer.SharedInfo.CurrencyId" asp-items="Model.CurrencyList" class="form-control"></select>
                    <label asp-for="Offer.SharedInfo.CurrencyId">Měna</label>
                </span>
                <span asp-validation-for="Offer.SharedInfo.CurrencyId" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Offer.SharedInfo.EstimatedFinishDate" class="col-lg-3 col-form-label form-control-label control-label"></label>
            <div class="col-lg-9 mycalendar">
                <span class="has-float-label">
                    <input asp-for="Offer.SharedInfo.EstimatedFinishDate" class="form-control" type="text" autocomplete="off" placeholder=" "/>
                    <label asp-for="Offer.SharedInfo.EstimatedFinishDate">Předpodkládaný termín ukončení</label>
                </span>
                <span asp-validation-for="Offer.SharedInfo.EstimatedFinishDate" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Offer.Notes" class="col-lg-3 col-form-label form-control-label control-label"></label>
            <div class="col-lg-9">
                <span class="has-float-label">
                    <textarea asp-for="Offer.Notes" class="form-control" placeholder=" "></textarea>
                    <label asp-for="Offer.Notes">Poznámky</label>
                </span>
                <span asp-validation-for="Offer.Notes" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-lg-3">
                <a asp-action="Index" class="btn btn-light border"><i class="fa fa-arrow-left"></i> Zpět</a>
            </div>
            <div class="col-lg-9">
                <input type="submit" class="btn btn-primary" value="Vytvořit nabídku" />
            </div>
        </div>

        </form>
    </div>
</div>

@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>

        // Clear and unselect '.select-contact-ajax' when '.select-company-ajax' changes it's value
        $('.select-company-ajax').on('select2:select', function (e) {
            $(".select-contact-ajax").val(null).empty().trigger('change');
        });

        $(document).ready(function(){

            // Add attribute when changing Selectlist value
            var originalHref = $('.modular-company-id').attr('href');
            $('#Offer_SharedInfo_CompanyId').change(function () {
                $('.modular-company-id').attr('href', originalHref + "?companyId=" + $(this).children('option:selected').val());
            })

            // DEFAULT VALUES
            // =======================================
            $('.select-department-ajax').append(new Option('@Html.Raw(Model.Offer.SharedInfo.EveDepartment)', '@Html.Raw(Model.Offer.SharedInfo.EveDepartment)', false, false)).trigger('change');
            $('.select-user-ajax').append(new Option('@Html.Raw(Model.Offer.SharedInfo.EveCreatedUser)', '@Html.Raw(Model.Offer.SharedInfo.EveCreatedUser)', false, false)).trigger('change');

            // INITIALIZATIONS
            // =======================================
            $('.mycalendar input').datepicker(datepickerParameters[0]);

            checkItemNameExists($("#Offer_OfferName"), 'Offers');

            $("#Offer_OfferName").keyup(function() {
                checkItemNameExists($(this), 'Offers');
            });


            function changeExchangeRate(curSymbol) {
                $.ajax({
                    url: '@Url.Action("getCurrencyStr", "Offers")',
                    type: 'GET',
                    cache: false,
                    data: { symbol: curSymbol },
                    success: function(res) {
                        $('#ExchangeRate').val(res);
                    }
                });
            }

            $('#CurrencyId').change(function() {
                var sel = document.getElementById('CurrencyId');
                var opt = sel.options[sel.selectedIndex];
                curSymbol = opt.text
                console.log("Changing... to " + curSymbol);
                changeExchangeRate(curSymbol);
            });

        })

    </script>

}